# Aspen Economics Extraction Configuration
# 配置文件用于自定义经济数据提取和分析参数

# 输出设置
output_directory: "economic_reports"
default_currency: "USD"
default_basis_year: 2024

# 成本因子配置
cost_factors:
  # 设备安装因子（典型值：2.0-3.0）
  installation_factor: 2.5
  
  # 工程设计费用（占设备成本百分比）
  engineering_rate: 0.12  # 12%
  
  # 施工管理费用（占设备成本百分比）
  construction_rate: 0.08  # 8%
  
  # 项目应急费用（占总成本百分比）
  contingency_rate: 0.15  # 15%
  
  # 材料修正因子
  material_factors:
    carbon_steel: 1.0      # 基准材料
    ss304: 2.1            # 304不锈钢
    ss316: 2.8            # 316不锈钢
    hastelloy_c: 8.5      # 哈氏合金C
    inconel: 12.0         # 因科镍合金
    titanium: 15.0        # 钛合金
  
  # 地区修正因子
  location_factors:
    us_gulf_coast: 1.0    # 美国墨西哥湾沿岸（基准）
    us_west_coast: 1.25   # 美国西海岸
    europe_western: 1.35  # 西欧
    asia_southeast: 0.75  # 东南亚
    china_eastern: 0.65   # 中国东部

# 财务参数
financial_parameters:
  # 项目生命周期（年）
  project_life: 20
  
  # 建设期（年）
  construction_period: 2
  
  # 启动期（年）
  startup_period: 1
  
  # 折现率
  discount_rate: 0.10  # 10%
  
  # 企业所得税率
  tax_rate: 0.25  # 25%
  
  # 折旧方式
  depreciation_method: "straight_line"
  
  # 折旧年限
  depreciation_life: 10
  
  # 流动资金率（占年销售额百分比）
  working_capital_rate: 0.05  # 5%

# 运营成本参数
opex_parameters:
  # 维护费用率（占CAPEX百分比）
  maintenance_rate: 0.04  # 4%
  
  # 保险费率（占CAPEX百分比）
  insurance_rate: 0.005  # 0.5%
  
  # 财产税率（占CAPEX百分比）
  property_tax_rate: 0.02  # 2%
  
  # 人工费率（占CAPEX百分比）
  labor_rate: 0.02  # 2%
  
  # 年操作小时数
  operating_hours: 8760  # 全年无休

# 公用工程价格（USD）
utility_prices:
  electricity: 0.08      # $/kWh
  steam_low_pressure: 25.0    # $/MT (低压蒸汽)
  steam_medium_pressure: 28.0 # $/MT (中压蒸汽)
  steam_high_pressure: 32.0   # $/MT (高压蒸汽)
  cooling_water: 0.05    # $/m³
  process_water: 0.5     # $/m³
  fuel_gas: 8.0         # $/GJ
  compressed_air: 0.02   # $/m³
  nitrogen: 0.15        # $/m³

# 原料价格（USD/MT）
raw_material_prices:
  hydrogen: 2000        # 氢气
  carbon_monoxide: 500  # 一氧化碳
  carbon_dioxide: 100   # 二氧化碳
  methane: 300         # 甲烷
  methanol: 400        # 甲醇
  ethanol: 600         # 乙醇
  water: 1             # 工业用水
  sodium_hydroxide: 800 # 氢氧化钠
  sulfuric_acid: 300   # 硫酸
  default: 500         # 默认价格

# 设备成本相关系数
equipment_costing:
  # 最小设备成本（USD）
  minimum_cost: 5000
  
  # 成本估算年份
  cost_basis_year: 2024
  
  # 设备类型成本系数
  cost_correlations:
    reactor:
      base_cost: 50000
      scaling_factor: 0.6
      size_parameter: "volume_m3"
      
    pump:
      base_cost: 5000
      scaling_factor: 0.7
      size_parameter: "power_kW"
      
    compressor:
      base_cost: 15000
      scaling_factor: 0.7
      size_parameter: "power_kW"
      
    heat_exchanger:
      base_cost: 1000
      scaling_factor: 0.65
      size_parameter: "area_m2"
      
    distillation_column:
      base_cost: 25000
      scaling_factor: 1.2
      size_parameter: "volume_m3"
      
    separator:
      base_cost: 20000
      scaling_factor: 0.6
      size_parameter: "volume_m3"
      
    tank:
      base_cost: 8000
      scaling_factor: 0.7
      size_parameter: "volume_m3"

# 报告生成设置
report_settings:
  # 包含的工作表
  worksheets:
    - "Executive Summary"
    - "CAPEX Breakdown"
    - "OPEX Analysis"
    - "Equipment Details"
    - "Financial Analysis"
    - "Sensitivity Analysis"
    - "Calculation Parameters"
    - "Assumptions & Notes"
  
  # 图表设置
  charts:
    enable_pie_charts: true
    enable_bar_charts: true
    enable_line_charts: true
    chart_colors:
      - "4472C4"  # 蓝色
      - "70AD47"  # 绿色
      - "FFC000"  # 橙色
      - "C5504B"  # 红色
      - "7030A0"  # 紫色
  
  # 格式设置
  formatting:
    currency_format: '"$"#,##0'
    percentage_format: '0.0%'
    number_format: '#,##0'
    date_format: 'yyyy-mm-dd'

# 数据质量和验证
data_validation:
  # 成本范围检查
  cost_range_checks:
    max_equipment_cost: 10000000  # $10M
    min_equipment_cost: 1000      # $1k
    max_total_capex: 1000000000   # $1B
    max_annual_opex: 500000000    # $500M
  
  # 参数合理性检查
  parameter_checks:
    max_temperature: 1500  # °C
    max_pressure: 300      # bar
    max_flow_rate: 1000000 # kg/hr
  
  # 警告阈值
  warning_thresholds:
    high_capex_per_equipment: 1000000  # $1M per equipment
    high_opex_ratio: 0.5              # OPEX/CAPEX ratio
    low_npv_threshold: -1000000       # Negative $1M NPV

# 敏感性分析参数
sensitivity_analysis:
  # 敏感性参数列表
  parameters:
    - name: "CAPEX"
      variations: [-30, -20, -10, 0, 10, 20, 30]  # 百分比变化
    - name: "OPEX"
      variations: [-30, -20, -10, 0, 10, 20, 30]
    - name: "Product Price"
      variations: [-30, -20, -10, 0, 10, 20, 30]
    - name: "Discount Rate"
      variations: [-3, -2, -1, 0, 1, 2, 3]  # 百分点变化
    - name: "Raw Material Cost"
      variations: [-30, -20, -10, 0, 10, 20, 30]
  
  # 评估指标
  evaluation_metrics:
    - "NPV"
    - "IRR"
    - "Payback Period"
    - "Production Cost"

# 日志和调试
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_to_file: true
  log_file: "aspen_economics_extraction.log"
  max_log_size: 10485760  # 10MB
  backup_count: 5

# 文件路径设置
file_paths:
  # 临时文件目录
  temp_directory: "temp"
  
  # 备份目录
  backup_directory: "backups"
  
  # 模板文件
  excel_template: null  # 如果有自定义模板
  
  # 输出文件命名模式
  output_filename_pattern: "{project_name}_Economic_Analysis_{timestamp}.xlsx"